name: Run Python Script

on:
  workflow_dispatch:

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Python Script
        run:
          pip install discord
          main.py